// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// loadpbi
DataFrame loadpbi(std::string filename);
RcppExport SEXP pbbamr_loadpbi(SEXP filenameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::string >::type filename(filenameSEXP);
    __result = Rcpp::wrap(loadpbi(filename));
    return __result;
END_RCPP
}
// loadDataAtOffsets
List loadDataAtOffsets(CharacterVector offsets, std::string bamName, std::string indexedFastaName);
RcppExport SEXP pbbamr_loadDataAtOffsets(SEXP offsetsSEXP, SEXP bamNameSEXP, SEXP indexedFastaNameSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< CharacterVector >::type offsets(offsetsSEXP);
    Rcpp::traits::input_parameter< std::string >::type bamName(bamNameSEXP);
    Rcpp::traits::input_parameter< std::string >::type indexedFastaName(indexedFastaNameSEXP);
    __result = Rcpp::wrap(loadDataAtOffsets(offsets, bamName, indexedFastaName));
    return __result;
END_RCPP
}
