# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Load PBI BAM index file
#'
#' This function loads a pbi index file into a dataframe.  Depending on the
#' number of attributes present, it will either load just the basic data, or optionally
#' the mapping and barcode data.
#'
#' @param filename A character vector with the file name in it.
#'
#' @export
#' @examples loadpbi("~git/pbbam/tests/data/dataset/bam_mapping_1.bam.pbi")
loadpbi <- function(filename) {
    .Call('pbbamr_loadpbi', PACKAGE = 'pbbamr', filename)
}

timesTwo <- function(x) {
    .Call('pbbamr_timesTwo', PACKAGE = 'pbbamr', x)
}

